CREATE TABLE DimProduto (
    ProdutoKey INT IDENTITY(1,1) PRIMARY KEY,
    ProdutoCodigoERP INT NOT NULL,
    Nome NVARCHAR(100) NOT NULL,
    Marca NVARCHAR(100) NOT NULL,
    Categoria NVARCHAR(100) NOT NULL,
    Modelo NVARCHAR(100) NOT NULL,
    Tipo NVARCHAR(50) NOT NULL,
    Cor NVARCHAR(50) NOT NULL,
    DataInicio DATE NOT NULL,
    DataFim DATE,
    IsAtual BIT NOT NULL DEFAULT 1
);
